spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ProductService
logging:
  level:
    feign: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html