spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: ProductService
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest