spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth_server
          uri: lb://AuthServer
          predicates:
            - Path=/v1/auth/**
        - id: product_server
          uri: lb://ProductService
          predicates:
            - Path=/v1/products/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthenticationFilter
        - id: product_server_category
          uri: lb://ProductService
          predicates:
            - Path=/v1/productsCategory/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthenticationFilter
        - id: file_storage_service
          uri: lb://FileStorage
          predicates:
            - Path=/v1/file/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthenticationFilter
        - id: wishlist_service
          uri: lb://Cart-And-WishList-Service
          predicates:
            - Path=/v1/wishlist/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthenticationFilter
        - id: cart_service
          uri: lb://Cart-And-WishList-Service
          predicates:
            - Path=/v1/cart/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthenticationFilter
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings
server:
  port: 8222
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5972