spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth_server
          uri: lb://AuthServer
          predicates:
            - Path=/v1/auth/**
        - id: product_server
          uri: lb://ProductService
          predicates:
            - Path=/v1/products/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthenticationFilter
server:
  port: 8222